name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: gem install bundler
    - run: bundle install
    - name: Run tests
      run: bundle exec fastlane testLane
